apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-avatares-back
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: avatares-back
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: avatares-back
    spec:
      containers:
      - image: rodosilva/avatares-back:1.0.0
        imagePullPolicy: Always
        name: avatares-back-container
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: configmap-avatares-back