apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-avatares-front
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: avatares-front
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: avatares-front
    spec:
      containers:
      - image: rodosilva/avatares-front:1.0.0
        imagePullPolicy: Always
        name: avatares-front-container
        ports:
        - containerPort: 5173
        envFrom:
          - configMapRef:
              name: configmap-avatares-front