apiVersion: v1
kind: Service
metadata:
  name: avatares-back
spec:
  selector:
    app.kubernetes.io/name: avatares-back
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: ClusterIP