apiVersion: v1
kind: Service
metadata:
  name: avatares-front
spec:
  selector:
    app.kubernetes.io/name: avatares-front
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer