name: Push Docker Images to Docker Hub

on: 
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setting Environment Variables
        id: envVariables
        run: |
          source ./backFront/.compose.env
          echo "BACK_VERSION=$BACK_VERSION"
          echo "FRONT_VERSION=$FRONT_VERSION"
          echo "BACK_VERSION=$BACK_VERSION" >> $GITHUB_ENV
          echo "FRONT_VERSION=$FRONT_VERSION" >> $GITHUB_ENV

        env:
          BACK_VERSION: $BACK_VERSION
          FRONT_VERSION: $FRONT_VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rodosilva/avatares-back

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd/
          push: true
          tags: rodosilva/avatares-back:${{BACK_VERSION}}